version: '3.0'

services:
  health-med-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: "pedidos-ms-postgres"
      DB_NAME: "healthmed"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"

    networks:
      - healthmed


  pedidos-ms-postgres:
    image: postgres:16
    container_name: pedidos-ms-postgres
    volumes:
      - ./docker/database/postgres:/application/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=healthmed
      - PGDATA=/application/postgres
    ports:
      - "5432:5432"
    networks:
      - healthmed
networks:
  healthmed:
    external: true